build_dir: 21-cadence-innovus-postroute
build_id: '21'
commands:
- ln -sf inputs/innovus-foundation-flow
- innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log
- cd outputs
- ln -sf ../checkpoints/design.checkpoint
debug:
- innovus -overwrite -64 -init innovus-foundation-flow/custom-scripts/run-debug.tcl
  -log logs/debug.log
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.checkpoint:
  - f: design.checkpoint
    step: 20-cadence-innovus-route
  innovus-foundation-flow:
  - f: innovus-foundation-flow
    step: 14-cadence-innovus-flowsetup
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 8-sram
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 8-sram
edges_o:
  design.checkpoint:
  - f: design.checkpoint
    step: 22-cadence-innovus-signoff
inputs:
- innovus-foundation-flow
- adk
- design.checkpoint
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
name: cadence-innovus-postroute
outputs:
- design.checkpoint
parameters:
  hold_target_slack: 0.005
  order:
  - setup-optmode.tcl
  - main.tcl
  setup_target_slack: 0.0
  useful_skew: true
postconditions:
- assert File( 'outputs/design.checkpoint' )
preconditions:
- assert Tool( 'innovus' )
- assert File( 'inputs/innovus-foundation-flow' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.checkpoint' )
source: /home/users/jeffreyy/ee372/mflowgen/steps/cadence-innovus-postroute
