build_dir: 24-open-magic-def2spice
build_id: '24'
commands:
- cp inputs/adk/magicrc .magicrc
- cp -L inputs/design.def.gz design.def.gz
- gunzip design.def.gz
- sed -i 's/\//____/g' design.def
- magic -noconsole -dnull extract.tcl | tee def2spice.log
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.def.gz:
  - f: design.def.gz
    step: 22-cadence-innovus-signoff
edges_o:
  design_extracted.spice:
  - f: design_extracted.spice
    step: 29-netgen-lvs-def
inputs:
- adk
- design.def.gz
name: open-magic-def2spice
outputs:
- design_extracted.spice
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/open-magic-def2spice
