build_dir: 28-gl-sim
build_id: '28'
commands:
- ./run.sh
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.args:
  - f: design.args.gls
    step: 10-testbench
  design.sdf:
  - f: design.sdf
    step: 27-synopsys-pt-timing-signoff
  design.vcs.v:
  - f: design.vcs.pg.v
    step: 22-cadence-innovus-signoff
  sky130_sram_1kbyte_1rw1r_32x256_8.v:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.v
    step: 8-sram
  testbench.sv:
  - f: testbench.sv
    step: 10-testbench
edges_o: {}
inputs:
- adk
- design.vcs.v
- testbench.sv
- design.sdf
- design.args
- instr_data.txt
- input_data.txt
- sky130_sram_1kbyte_1rw1r_32x256_8.v
name: gl-sim
outputs:
- run.fsdb
parameters:
  dut_name: accelerator_inst
  testbench_name: accelerator_tb
  waveform: true
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/synopsys-vcs-sim-sdf
