build_dir: 5-pin-placement
build_id: '5'
commands:
- 'true'
edges_i: {}
edges_o:
  pin-assignments.tcl:
  - f: pin-assignments.tcl
    step: 15-cadence-innovus-init
name: pin-placement
outputs:
- pin-assignments.tcl
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/pin-placement
