build_dir: 3-gen-saif-gl
build_id: '3'
commands:
- vcd2saif -input inputs/run.vcd -output outputs/run.saif
edges_i: {}
edges_o:
  run.saif:
  - f: run.saif
    step: 25-ptpx-gl
inputs:
- run.vcd
name: gen-saif-gl
outputs:
- run.saif
source: /home/users/jeffreyy/ee372/mflowgen/steps/synopsys-vcd2saif-convert
