build_dir: 4-info
build_id: '4'
commands:
- echo "Design name      -- accelerator"
- echo "Clock period     -- 20.0"
- echo "ADK              -- skywater-130nm-adk"
- echo "ADK view         -- view-standard"
- echo
- echo "Constructed from -- /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/construct.py"
- echo
edges_i: {}
edges_o: {}
name: info
parameters:
  adk: skywater-130nm-adk
  adk_view: view-standard
  clock_period: 20.0
  construct_path: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/construct.py
  design_name: accelerator
source: /home/users/jeffreyy/ee372/mflowgen/steps/info
