build_dir: 31-open-magic-drc
build_id: '31'
commands:
- cp inputs/adk/magicrc .magicrc
- magic -noconsole -dnull run_drc.tcl | tee outputs/drc_results.log
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design_merged.gds:
  - f: design_merged.gds
    step: 23-mentor-calibre-gdsmerge
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 8-sram
edges_o: {}
inputs:
- adk
- design_merged.gds
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
name: open-magic-drc
outputs:
- drc_results.log
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/open-magic-drc
