build_dir: 1-custom-flowstep
build_id: '1'
commands:
- 'true'
edges_i: {}
edges_o:
  setup.tcl:
  - f: setup.tcl
    step: 14-cadence-innovus-flowsetup
name: custom-flowstep
outputs:
- setup.tcl
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/custom-flowstep
