build_dir: 13-synopsys-dc-synthesis
build_id: '13'
commands:
- bash run.sh
debug:
- export DC_EXIT_AFTER_SETUP=1
- ln -sf results/*.mapped.ddc debug.ddc
- design_vision-xg -topographical -x "source START.tcl; read_ddc debug.ddc"
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  compile.tcl:
  - f: compile.tcl
    step: 9-synopsys-dc-compile
  constraints.tcl:
  - f: constraints.tcl
    step: 0-constraints
  design.v:
  - f: design.v
    step: 6-rtl
  run.saif:
  - f: run.saif
    step: 12-gen-saif-rtl
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 8-sram
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
    step: 8-sram
edges_o:
  design.namemap:
  - f: design.namemap
    step: 26-ptpx-rtl
  design.sdc:
  - f: design.sdc
    step: 14-cadence-innovus-flowsetup
  - f: design.sdc
    step: 15-cadence-innovus-init
  - f: design.sdc
    step: 16-cadence-innovus-power
  - f: design.sdc
    step: 17-cadence-innovus-place
  - f: design.sdc
    step: 18-cadence-innovus-cts
  - f: design.pt.sdc
    step: 27-synopsys-pt-timing-signoff
  - f: design.pt.sdc
    step: 26-ptpx-rtl
  - f: design.pt.sdc
    step: 25-ptpx-gl
  design.v:
  - f: design.v
    step: 14-cadence-innovus-flowsetup
  - f: design.v
    step: 15-cadence-innovus-init
inputs:
- adk
- design.v
- constraints.tcl
- run.saif
- design.upf
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
- compile.tcl
name: synopsys-dc-synthesis
outputs:
- design.v
- design.sdc
- design.namemap
- design.svf
- design.upf
parameters:
  clock_period: 20.0
  design_name: accelerator
  flatten_effort: 0
  gate_clock: true
  high_effort_area_opt: false
  nthreads: 16
  order:
  - designer-interface.tcl
  - setup-session.tcl
  - read-design.tcl
  - constraints.tcl
  - make-path-groups.tcl
  - compile-options.tcl
  - compile.tcl
  - generate-results.tcl
  - reporting.tcl
  saif_instance: accelerator_tb/accelerator_inst
  suppress_msg: false
  suppressed_msg:
  - TFCHK-072
  - TFCHK-014
  - TFCHK-049
  - TFCHK-050
  - TFCHK-012
  - TFCHK-073
  - TFCHK-092
  - PSYN-651
  - PSYN-650
  topographical: true
  uniquify_with_design_name: true
postconditions:
- assert File( 'outputs/design.v' )
- assert File( 'outputs/design.sdc' )
- assert 'error:' not in File( 'logs/dc.log' )
- assert 'Unresolved references' not in File( 'logs/dc.log' )
- assert 'Unable to resolve' not in File( 'logs/dc.log' )
- assert 'Presto compilation terminated' not in File( 'logs/dc.log' )
- assert 'GTECH' not in File( 'outputs/design.v' )
- assert 'ELAB-405' not in File( 'logs/dc.log' )
- assert 'PSYN-024' not in File( 'logs/dc.log' )
- assert 'PSYN-025' not in File( 'logs/dc.log' )
- assert 'PSYN-039' not in File( 'logs/dc.log' )
- assert 'create_clock' in File( 'outputs/design.sdc' )
- |
  from assertion_helpers import percent_clock_gated, n_regs
  if n_regs() > 10:
    assert percent_clock_gated() > 0.50
preconditions:
- assert Tool( 'dc_shell-xg-t' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.v' )
- assert File( 'inputs/constraints.tcl' )
source: /home/users/jeffreyy/ee372/mflowgen/steps/synopsys-dc-synthesis
