build_dir: 35-mentor-calibre-comparison-nobbox
build_id: '35'
commands:
- sh run_lvs.sh
debug:
- calibre -rve -lvs svdb
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design_extracted.spice:
  - f: design_extracted.spice
    step: 33-open-magic-gds2spice-nobbox
  sky130_sram_1kbyte_1rw1r_32x256_8.sp:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.sp
    step: 8-sram
edges_o: {}
inputs:
- adk
- design_extracted.spice
- design.flatbuslvs.v
- sky130_sram_1kbyte_1rw1r_32x256_8.sp
name: mentor-calibre-comparison-nobbox
outputs:
- lvs.report
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/mentor-calibre-comparison-nobbox
