build_dir: 33-open-magic-gds2spice-nobbox
build_id: '33'
commands:
- cp inputs/adk/magicrc .magicrc
- magic -noconsole -dnull extract.tcl | tee gds2spice.log
- mv accelerator.spice outputs/design_extracted.spice
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design_merged.gds:
  - f: design_merged.gds
    step: 23-mentor-calibre-gdsmerge
edges_o:
  design_extracted.spice:
  - f: design_extracted.spice
    step: 36-netgen-lvs-gds
  - f: design_extracted.spice
    step: 35-mentor-calibre-comparison-nobbox
inputs:
- adk
- design_merged.gds
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
name: open-magic-gds2spice-nobbox
outputs:
- design_extracted.spice
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/open-magic-gds2spice-nobbox
