build_dir: 36-netgen-lvs-gds
build_id: '36'
commands:
- sh run_lvs.sh
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.lvs.v:
  - f: design.lvs.v
    step: 22-cadence-innovus-signoff
  design_extracted.spice:
  - f: design_extracted.spice
    step: 33-open-magic-gds2spice-nobbox
edges_o: {}
inputs:
- adk
- design_extracted.spice
- design.lvs.v
name: netgen-lvs-gds
outputs:
- lvs_results.log
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/netgen-lvs-gds
