build_dir: 2-floorplan
build_id: '2'
commands:
- 'true'
edges_i: {}
edges_o:
  floorplan.tcl:
  - f: floorplan.tcl
    step: 15-cadence-innovus-init
name: floorplan
outputs:
- floorplan.tcl
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/floorplan
