build_dir: 9-synopsys-dc-compile
build_id: '9'
commands:
- 'true'
edges_i: {}
edges_o:
  compile.tcl:
  - f: compile.tcl
    step: 13-synopsys-dc-synthesis
name: synopsys-dc-compile
outputs:
- compile.tcl
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/synopsys-dc-compile
