build_dir: 14-cadence-innovus-flowsetup
build_id: '14'
commands:
- source ./run.sh
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.sdc:
  - f: design.sdc
    step: 13-synopsys-dc-synthesis
  design.v:
  - f: design.v
    step: 13-synopsys-dc-synthesis
  setup.tcl:
  - f: setup.tcl
    step: 1-custom-flowstep
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 8-sram
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 8-sram
edges_o:
  innovus-foundation-flow:
  - f: innovus-foundation-flow
    step: 15-cadence-innovus-init
  - f: innovus-foundation-flow
    step: 16-cadence-innovus-power
  - f: innovus-foundation-flow
    step: 17-cadence-innovus-place
  - f: innovus-foundation-flow
    step: 18-cadence-innovus-cts
  - f: innovus-foundation-flow
    step: 19-cadence-innovus-postcts_hold
  - f: innovus-foundation-flow
    step: 20-cadence-innovus-route
  - f: innovus-foundation-flow
    step: 21-cadence-innovus-postroute
  - f: innovus-foundation-flow
    step: 22-cadence-innovus-signoff
inputs:
- adk
- design.v
- design.sdc
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
- setup.tcl
name: cadence-innovus-flowsetup
outputs:
- innovus-foundation-flow
parameters:
  design_name: accelerator
  express_flow: false
  nthreads: 16
  skip_verify_connectivity: false
postconditions:
- assert File( 'outputs/innovus-foundation-flow' )
preconditions:
- assert Tool( 'innovus' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.sdc' )
- assert File( 'inputs/design.v' )
source: /home/users/jeffreyy/ee372/mflowgen/steps/cadence-innovus-flowsetup
