build_dir: 10-testbench
build_id: '10'
commands:
- cp accelerator_tb.sv outputs/testbench.sv
- cp instr_data.txt outputs/instr_data.txt
- cp input_data.txt outputs/input_data.txt
- cp design.vcs.args outputs/design.args
- cp design.vcs.args.gls outputs/design.args.gls
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
edges_o:
  design.args:
  - f: design.args
    step: 11-rtl-sim
  design.args.gls:
  - f: design.args
    step: 28-gl-sim
  input_data.txt:
  - f: input_data.txt
    step: 11-rtl-sim
  instr_data.txt:
  - f: instr_data.txt
    step: 11-rtl-sim
  testbench.sv:
  - f: testbench.sv
    step: 11-rtl-sim
  - f: testbench.sv
    step: 28-gl-sim
inputs:
- adk
name: testbench
outputs:
- testbench.sv
- instr_data.txt
- input_data.txt
- design.args
- design.args.gls
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/testbench
