build_dir: 27-synopsys-pt-timing-signoff
build_id: '27'
commands:
- mkdir -p reports
- pt_shell -file pt.tcl
- mkdir -p outputs && cd outputs
- ln -sf ../design.sdf design.sdf
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.pt.sdc:
  - f: design.sdc
    step: 13-synopsys-dc-synthesis
  design.spef.gz:
  - f: design.spef.gz
    step: 22-cadence-innovus-signoff
  design.vcs.v:
  - f: design.vcs.v
    step: 22-cadence-innovus-signoff
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
    step: 8-sram
edges_o:
  design.sdf:
  - f: design.sdf
    step: 28-gl-sim
inputs:
- adk
- design.vcs.v
- design.pt.sdc
- design.spef.gz
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
name: synopsys-pt-timing-signoff
outputs:
- design.sdf
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/synopsys-pt-timing-signoff
