build_dir: 8-sram
build_id: '8'
commands:
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.sp              outputs/sky130_sram_1kbyte_1rw1r_32x256_8.sp
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lvs.sp          outputs/sky130_sram_1kbyte_1rw1r_32x256_8.lvs.sp
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.v               outputs/sky130_sram_1kbyte_1rw1r_32x256_8.v
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lef             outputs/sky130_sram_1kbyte_1rw1r_32x256_8.lef
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
  outputs/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.gds             outputs/sky130_sram_1kbyte_1rw1r_32x256_8.gds
- cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db  outputs/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
- sed -i '/SHAPE ABUTMENT/d' outputs/sky130_sram_1kbyte_1rw1r_32x256_8.lef
edges_i: {}
edges_o:
  sky130_sram_1kbyte_1rw1r_32x256_8.gds:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.gds
    step: 23-mentor-calibre-gdsmerge
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 13-synopsys-dc-synthesis
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 14-cadence-innovus-flowsetup
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 15-cadence-innovus-init
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 16-cadence-innovus-power
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 17-cadence-innovus-place
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 18-cadence-innovus-cts
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 19-cadence-innovus-postcts_hold
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 20-cadence-innovus-route
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 21-cadence-innovus-postroute
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 22-cadence-innovus-signoff
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 31-open-magic-drc
  sky130_sram_1kbyte_1rw1r_32x256_8.sp:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.sp
    step: 34-mentor-calibre-comparison
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.sp
    step: 35-mentor-calibre-comparison-nobbox
  sky130_sram_1kbyte_1rw1r_32x256_8.v:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.v
    step: 11-rtl-sim
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.v
    step: 28-gl-sim
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
    step: 13-synopsys-dc-synthesis
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
    step: 27-synopsys-pt-timing-signoff
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
    step: 26-ptpx-rtl
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
    step: 25-ptpx-gl
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 14-cadence-innovus-flowsetup
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 15-cadence-innovus-init
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 16-cadence-innovus-power
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 17-cadence-innovus-place
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 18-cadence-innovus-cts
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 19-cadence-innovus-postcts_hold
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 20-cadence-innovus-route
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 21-cadence-innovus-postroute
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 22-cadence-innovus-signoff
name: sram
outputs:
- sky130_sram_1kbyte_1rw1r_32x256_8.sp
- sky130_sram_1kbyte_1rw1r_32x256_8.lvs.sp
- sky130_sram_1kbyte_1rw1r_32x256_8.v
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
- sky130_sram_1kbyte_1rw1r_32x256_8.gds
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/sram
