build_dir: 15-cadence-innovus-init
build_id: '15'
commands:
- ln -sf inputs/innovus-foundation-flow
- innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log
- cd outputs
- ln -sf ../checkpoints/design.checkpoint
debug:
- innovus -overwrite -64 -init innovus-foundation-flow/custom-scripts/run-debug.tcl
  -log logs/debug.log
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.sdc:
  - f: design.sdc
    step: 13-synopsys-dc-synthesis
  design.v:
  - f: design.v
    step: 13-synopsys-dc-synthesis
  floorplan.tcl:
  - f: floorplan.tcl
    step: 2-floorplan
  innovus-foundation-flow:
  - f: innovus-foundation-flow
    step: 14-cadence-innovus-flowsetup
  pin-assignments.tcl:
  - f: pin-assignments.tcl
    step: 5-pin-placement
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 8-sram
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 8-sram
edges_o:
  design.checkpoint:
  - f: design.checkpoint
    step: 16-cadence-innovus-power
inputs:
- innovus-foundation-flow
- adk
- design.v
- design.sdc
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
- floorplan.tcl
- pin-assignments.tcl
name: cadence-innovus-init
outputs:
- design.checkpoint
parameters:
  order:
  - main.tcl
  - quality-of-life.tcl
  - floorplan.tcl
  - add-endcaps-welltaps.tcl
  - pin-assignments.tcl
  - make-path-groups.tcl
  - reporting.tcl
postconditions:
- assert File( 'outputs/design.checkpoint' )
- assert 'Inconsistency detected in the capacitance units' not in File( 'logs/run.log'
  )
preconditions:
- assert Tool( 'innovus' )
- assert File( 'inputs/innovus-foundation-flow' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.v' )
- assert File( 'inputs/design.sdc' )
source: /home/users/jeffreyy/ee372/mflowgen/steps/cadence-innovus-init
