build_dir: 17-cadence-innovus-place
build_id: '17'
commands:
- ln -sf inputs/innovus-foundation-flow
- innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log
- cd outputs
- ln -sf ../checkpoints/design.checkpoint
debug:
- innovus -overwrite -64 -init innovus-foundation-flow/custom-scripts/run-debug.tcl
  -log logs/debug.log
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.checkpoint:
  - f: design.checkpoint
    step: 16-cadence-innovus-power
  design.sdc:
  - f: design.sdc
    step: 13-synopsys-dc-synthesis
  innovus-foundation-flow:
  - f: innovus-foundation-flow
    step: 14-cadence-innovus-flowsetup
  sky130_sram_1kbyte_1rw1r_32x256_8.lef:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8.lef
    step: 8-sram
  sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib:
  - f: sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    step: 8-sram
edges_o:
  design.checkpoint:
  - f: design.checkpoint
    step: 18-cadence-innovus-cts
inputs:
- innovus-foundation-flow
- adk
- design.sdc
- design.checkpoint
- sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
- sky130_sram_1kbyte_1rw1r_32x256_8.lef
name: cadence-innovus-place
outputs:
- design.checkpoint
parameters:
  cell_padding: 2
  order:
  - setup-optmode.tcl
  - setup-cellpad.tcl
  - setup-inst-gap.tcl
  - main.tcl
  - clean-cellpad.tcl
  - reporting.tcl
  useful_skew: true
postconditions:
- assert File( 'outputs/design.checkpoint' )
preconditions:
- assert Tool( 'innovus' )
- assert File( 'inputs/innovus-foundation-flow' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/design.sdc' )
- assert File( 'inputs/design.checkpoint' )
source: /home/users/jeffreyy/ee372/mflowgen/steps/cadence-innovus-place
