build_dir: 29-netgen-lvs-def
build_id: '29'
commands:
- sh run_lvs.sh
edges_i:
  adk:
  - f: adk
    step: 7-skywater-130nm
  design.lvs.v:
  - f: design.lvs.v
    step: 22-cadence-innovus-signoff
  design_extracted.spice:
  - f: design_extracted.spice
    step: 24-open-magic-def2spice
edges_o: {}
inputs:
- adk
- design_extracted.spice
- design.lvs.v
name: netgen-lvs-def
outputs:
- lvs_results.log
parameters:
  design_name: accelerator
source: /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/netgen-lvs-def
